# Generated by Django 5.2.8 on 2025-12-03 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('operator', 'Оператор фулфилмента'), ('logistic', 'Логист'), ('admin', 'Администратор')], default='operator', max_length=20)),
                ('fulfillment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фулфилмент оператор')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
