# Generated by Django 5.2.8 on 2026-01-11 23:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('legal', 'Юридическое лицо (ООО, АО)'), ('entrepreneur', 'Индивидуальный предприниматель (ИП)'), ('individual', 'Физическое лицо'), ('self_employed', 'Самозанятый')], default='legal', max_length=20, verbose_name='Тип контрагента')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование/ФИО')),
                ('full_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Полное наименование')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, null=True, verbose_name='Фактический адрес')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 или 12 цифр', regex='^[0-9]{10,12}$')], verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='КПП должен содержать 9 цифр', regex='^[0-9]{9}$')], verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='ОГРН должен содержать 13 или 15 цифр', regex='^[0-9]{13,15}$')], verbose_name='ОГРН/ОГРНИП')),
                ('passport_series', models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.TextField(blank=True, null=True, verbose_name='Кем выдан паспорт')),
                ('passport_issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('director_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО руководителя')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='Контактное лицо')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк')),
                ('bank_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет')),
                ('bank_bik', models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК')),
                ('bank_correspondent_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Поставщик')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Покупатель')),
                ('is_carrier', models.BooleanField(default=False, verbose_name='Перевозчик')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='counterpart_name_6b080f_idx'), models.Index(fields=['inn'], name='counterpart_inn_bcaee1_idx'), models.Index(fields=['type'], name='counterpart_type_9da656_idx'), models.Index(fields=['is_active'], name='counterpart_is_acti_a135ac_idx')],
            },
        ),
    ]
