# Generated by Django 5.2.8 on 2025-12-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logistic", "0002_deliveryorder_operator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_date", models.DateField(verbose_name="Дата забора")),
                (
                    "pickup_address",
                    models.CharField(
                        help_text="Город, улица, дом, помещение",
                        max_length=500,
                        verbose_name="Адрес забора",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Клиент/Компания"),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Телефон клиента",
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email клиента",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество мест")),
                (
                    "weight",
                    models.FloatField(blank=True, null=True, verbose_name="Вес (кг)"),
                ),
                (
                    "volume",
                    models.FloatField(blank=True, null=True, verbose_name="Объем (м³)"),
                ),
                (
                    "cargo_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание груза"
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Хрупкий груз, температура, сроки и т.д.",
                        null=True,
                        verbose_name="Особые требования",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("confirmed", "Подтверждена"),
                            ("picked_up", "Забран"),
                            ("cancelled", "Отменена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Внутренние заметки"
                    ),
                ),
                (
                    "delivery_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_source",
                        to="logistic.deliveryorder",
                        verbose_name="Связанная заявка на доставку",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный оператор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на забор груза",
                "verbose_name_plural": "Заявки на забор груза",
                "ordering": ["-pickup_date", "-created_at"],
            },
        ),
    ]
