# Generated by Django 5.2.8 on 2025-12-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/pickup/', verbose_name='QR-код'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Сквозной номер заказа'),
        ),
    ]
