# Generated by Django 5.2.8 on 2025-12-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_pickuporder_qr_code_pickuporder_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='client_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование компании'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Полный адрес доставки, включая город, улицу, дом', null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='desired_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Желаемая дата поставки'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='marketplace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Маркетплейс'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='order_1c_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='№ заказа в 1С'),
        ),
    ]
