# Generated by Django 5.2.8 on 2025-12-12 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0003_pickuporder_client_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='cargo_description',
            field=models.TextField(blank=True, default='', help_text='Дополнительная информация о заказе', null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='client_company',
            field=models.CharField(default='Не указано', help_text='Полное наименование компании/ИП', max_length=200, verbose_name='Наименование компании'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='client_email',
            field=models.EmailField(default='noemail@example.com', help_text='Email для отправки подтверждения', max_length=254, verbose_name='Email клиента'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='client_name',
            field=models.CharField(default='Не указано', help_text='ФИО контактного лица', max_length=200, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='client_phone',
            field=models.CharField(default='Не указан', help_text='Телефон для связи', max_length=20, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='delivery_address',
            field=models.TextField(default='Не указан', help_text='Полный адрес доставки', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='desired_delivery_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата, когда клиент хочет получить заказ', verbose_name='Желаемая дата поставки'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='marketplace',
            field=models.CharField(choices=[('Wildberries', 'Wildberries'), ('Ozon', 'Ozon'), ('Яндекс.Маркет', 'Яндекс.Маркет'), ('SberMarket', 'SberMarket'), ('Собственный сайт', 'Собственный сайт'), ('Другое', 'Другое')], default='Собственный сайт', help_text='Площадка, с которой заказ', max_length=50, verbose_name='Маркетплейс'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Внутренние заметки'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='order_1c_number',
            field=models.CharField(blank=True, help_text='Номер заказа в системе 1С', max_length=50, null=True, verbose_name='№ заказа в 1С'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='pickup_address',
            field=models.CharField(default='Не указан', help_text='Город, улица, дом, помещение', max_length=500, verbose_name='Адрес забора'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='pickup_date',
            field=models.DateField(blank=True, help_text='Дата будет назначена оператором после подтверждения', null=True, verbose_name='Дата забора'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='special_requirements',
            field=models.TextField(blank=True, default='', help_text='Хрупкий груз, температура, сроки и т.д.', null=True, verbose_name='Особые требования'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='volume',
            field=models.FloatField(default=0.0, verbose_name='Объем (м³)'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Вес (кг)'),
        ),
    ]
