# Generated by Django 5.2.8 on 2025-12-18 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0004_alter_pickuporder_cargo_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='contact_person',
            field=models.CharField(blank=True, help_text='ФИО лица, которое будет выдавать груз', max_length=200, null=True, verbose_name='Контактное лицо для выдачи груза'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Номер транспортной накладной', max_length=100, null=True, verbose_name='Номер накладной'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='pickup_time',
            field=models.TimeField(blank=True, help_text='Время, когда нужно забрать груз', null=True, verbose_name='Время забора'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='receiving_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_orders', to=settings.AUTH_USER_MODEL, verbose_name='Оператор приемки'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='receiving_warehouse',
            field=models.CharField(blank=True, help_text='Склад, куда будет доставлен груз', max_length=200, null=True, verbose_name='Склад приемки'),
        ),
    ]
