# Generated by Django 5.2.8 on 2025-12-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0005_pickuporder_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='status',
            field=models.CharField(choices=[('ready', 'Готов к выдаче'), ('payment', 'На оплате')], default='new', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
