# Generated by Django 5.2.8 on 2025-12-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0006_alter_pickuporder_status'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuporder',
            options={'ordering': ['-pickup_date', '-created_at'], 'verbose_name': 'Заявки на забор груза', 'verbose_name_plural': 'Заявки на забор груза'},
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='delivery_city',
            field=models.ForeignKey(blank=True, help_text='Город назначения доставки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_orders', to='warehouses.city', verbose_name='Город доставки'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='receiving_warehouse',
            field=models.ForeignKey(blank=True, help_text='Склад, куда будет доставлен груз', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_orders', to='warehouses.warehouse', verbose_name='Склад приемки'),
        ),
    ]
