# Generated by Django 5.2.8 on 2025-12-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0007_alter_pickuporder_options_pickuporder_delivery_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuporder',
            name='pickup_time',
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='pickup_time_from',
            field=models.TimeField(blank=True, help_text='Начало интервала забора', null=True, verbose_name='Время забора от'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='pickup_time_to',
            field=models.TimeField(blank=True, help_text='Конец интервала забора', null=True, verbose_name='Время забора до'),
        ),
    ]
