# Generated by Django 5.2.8 on 2026-01-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
        ('pickup', '0008_remove_pickuporder_pickup_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuporder',
            name='client_company',
        ),
        migrations.RemoveField(
            model_name='pickuporder',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='pickuporder',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='pickuporder',
            name='client_phone',
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Контрагент, который получает груз', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_pickup_orders', to='counterparties.counterparty', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Контрагент, который отправляет груз', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_pickup_orders', to='counterparties.counterparty', verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='status',
            field=models.CharField(choices=[('ready', 'Готов к выдаче'), ('payment', 'На оплате')], default='ready', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
