# Generated by Django 5.2.8 on 2026-02-03 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0009_remove_pickuporder_client_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное наименование компании перевозчика', max_length=200, verbose_name='Название перевозчика')),
                ('contact_person', models.CharField(blank=True, help_text='ФИО контактного лица перевозчика', max_length=200, null=True, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, help_text='Телефон перевозчика', max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='Email перевозчика', max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли перевозчика в выпадающих списках', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Перевозчик',
                'verbose_name_plural': 'Перевозчики',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='carrier',
            field=models.ForeignKey(blank=True, help_text='Компания перевозчик для забора груза', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_orders', to='pickup.carrier', verbose_name='Перевозчик'),
        ),
    ]
