# Generated by Django 5.2.8 on 2026-02-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0010_carrier_pickuporder_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='status',
            field=models.CharField(choices=[('ready', 'Готов к выдаче'), ('payment', 'На оплате'), ('accepted', 'Принят')], default='ready', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
