# Generated by Django 5.2.8 on 2026-02-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0011_alter_pickuporder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='status',
            field=models.CharField(choices=[('ready', 'Готова к выдаче'), ('payment', 'На оплате'), ('accepted', 'Принята')], default='ready', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
