# Generated by Django 5.2.8 on 2026-02-05 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0012_alter_pickuporder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='logistic',
            field=models.ForeignKey(blank=True, help_text='Логист, ответственный за заявку', limit_choices_to={'profile__role': 'logistic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistic_pickup_orders', to=settings.AUTH_USER_MODEL, verbose_name='Логист'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='receiving_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_orders', to=settings.AUTH_USER_MODEL, verbose_name='Оператор фулфилмента'),
        ),
    ]
