# Generated by Django 5.2.8 on 2026-02-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0013_pickuporder_logistic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='shipment_date',
            field=models.DateField(blank=True, help_text='Дата, когда груз был отгружен со склада', null=True, verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='status',
            field=models.CharField(choices=[('ready', 'Готова к выдаче'), ('payment', 'На оплате'), ('in_transit', 'В пути'), ('accepted', 'Принята')], default='ready', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
