# Generated by Django 5.2.8 on 2026-03-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0015_alter_pickuporder_logistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuporder',
            name='shipment_date',
        ),
    ]
