# Generated by Django 5.2.8 on 2026-03-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0016_remove_pickuporder_shipment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuporder',
            name='marketplace',
        ),
    ]
