# Generated by Django 5.2.8 on 2025-12-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата доставки')),
                ('city', models.CharField(max_length=100, verbose_name='Город назначения')),
                ('warehouse', models.CharField(max_length=100, verbose_name='Склад отправки')),
                ('fulfillment', models.CharField(max_length=100, verbose_name='Фулфилмент оператор')),
                ('quantity', models.IntegerField(verbose_name='Количество мест')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('volume', models.FloatField(verbose_name='Объем (м³)')),
                ('status', models.CharField(choices=[('submitted', 'Заявка подана'), ('driver_assigned', 'Назначен водитель'), ('shipped', 'Отправлено')], default='submitted', max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО водителя')),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон водителя')),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка и номер ТС')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
