# Generated by Django 5.2.8 on 2025-12-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_deliveryorder_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/delivery/', verbose_name='QR-код'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Сквозной номер заказа'),
        ),
    ]
