# Generated by Django 5.2.8 on 2025-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_alter_deliveryorder_options_deliveryorder_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на доставку', 'verbose_name_plural': 'Заявки на доставку'},
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='driver_pass_info',
            field=models.CharField(blank=True, help_text='Номер пропуска, серия, срок действия и т.д.', max_length=200, null=True, verbose_name='Данные пропуска'),
        ),
    ]
