# Generated by Django 5.2.8 on 2025-12-22 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_alter_deliveryorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='fulfillment',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'operator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to=settings.AUTH_USER_MODEL, verbose_name='Фулфилмент оператор'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный оператор'),
        ),
    ]
