# Generated by Django 5.2.8 on 2025-12-23 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_alter_deliveryorder_fulfillment_and_more'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='warehouses.city', verbose_name='Город назначения'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='warehouses.warehouse', verbose_name='Склад отправки'),
        ),
    ]
