# Generated by Django 5.2.8 on 2025-12-23 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0006_alter_deliveryorder_city_and_more'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Заполняется, если доставка не на склад', null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='receiving_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_receiving_orders', to='warehouses.warehouse', verbose_name='Склад приемки'),
        ),
    ]
