# Generated by Django 5.2.8 on 2025-12-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_deliveryorder_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='receiving_warehouse',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='pickup_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес отправки'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
    ]
