# Generated by Django 5.2.8 on 2026-01-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
        ('logistic', '0008_remove_deliveryorder_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='pickup_address',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Контрагент, который получает груз', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_deliveries', to='counterparties.counterparty', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='recipient_address',
            field=models.TextField(blank=True, help_text='Можно указать вручную, если получатель не выбран', null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Контрагент, который отправляет груз', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_deliveries', to='counterparties.counterparty', verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='sender_address',
            field=models.TextField(blank=True, help_text='Можно указать вручную, если отправитель не выбран', null=True, verbose_name='Адрес отправки'),
        ),
    ]
