# Generated by Django 5.2.8 on 2026-01-21 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0010_rename_address_fields'),
        ('warehouses', '0005_remove_warehouseschedule_is_24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_city',
            field=models.ForeignKey(blank=True, help_text='Город назначения доставки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='warehouses.city', verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_warehouse',
            field=models.ForeignKey(blank=True, help_text='Склад, куда доставляется груз', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_delivery_orders', to='warehouses.warehouse', verbose_name='Склад доставки'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='pickup_warehouse',
            field=models.ForeignKey(blank=True, help_text='Склад, откуда отправляется груз', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_delivery_orders', to='warehouses.warehouse', verbose_name='Склад отправки'),
        ),
    ]
