# Generated by Django 5.2.8 on 2026-02-06 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0011_deliveryorder_delivery_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='fulfillment',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='logistic',
            field=models.ForeignKey(blank=True, help_text='Логист, ответственный за заявку', limit_choices_to={'profile__role': 'logistic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistic_delivery_orders', to=settings.AUTH_USER_MODEL, verbose_name='Логист'),
        ),
    ]
