# Generated by Django 5.2.8 on 2026-02-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0012_remove_deliveryorder_fulfillment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Заявка подана'), ('driver_assigned', 'Назначен водитель'), ('on_the_way', 'В пути'), ('shipped', 'Отправлено')], default='submitted', max_length=20),
        ),
    ]
