# Generated by Django 5.2.8 on 2026-03-10 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0013_alter_deliveryorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='logistic',
            field=models.ForeignKey(blank=True, help_text='Логист, ответственный за заявку', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistic_delivery_orders', to=settings.AUTH_USER_MODEL, verbose_name='Логист'),
        ),
    ]
