# Generated by Django 5.2.8 on 2026-03-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0014_alter_deliveryorder_logistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='date',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='fulfilled_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поставки на МП'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='shipped_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки со склада'),
        ),
    ]
