# Generated by Django 5.2.8 on 2026-03-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0015_remove_deliveryorder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='fulfilled_at',
        ),
    ]
