# Generated by Django 5.2.8 on 2025-12-21 09:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название города')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион/Область')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тары')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код тары')),
                ('category', models.CharField(choices=[('pallet', 'Паллеты'), ('box', 'Коробки'), ('bag', 'Мешки'), ('drum', 'Бочки'), ('container', 'Контейнеры'), ('other', 'Прочее')], max_length=20, verbose_name='Категория')),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длина (см)')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ширина (см)')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Высота (см)')),
                ('weight_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Грузоподъемность (кг)')),
                ('volume', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем (м³)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_reusable', models.BooleanField(default=False, verbose_name='Многоразовая')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена закупки')),
                ('rental_price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Аренда в сутки')),
            ],
            options={
                'verbose_name': 'Тип тары',
                'verbose_name_plural': 'Типы тары',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название склада')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код склада')),
                ('address', models.TextField(verbose_name='Адрес склада')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон склада')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email склада')),
                ('total_area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая площадь (м²)')),
                ('available_area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доступная площадь (м²)')),
                ('opening_time', models.TimeField(blank=True, default=datetime.time(9, 0), null=True, verbose_name='Время открытия')),
                ('closing_time', models.TimeField(blank=True, default=datetime.time(18, 0), null=True, verbose_name='Время закрытия')),
                ('work_days', models.CharField(blank=True, default='пн-пт', help_text='пн-пт, сб, вс', max_length=100, null=True, verbose_name='Рабочие дни')),
                ('is_24h', models.BooleanField(default=False, verbose_name='Круглосуточный')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='warehouses.city', verbose_name='Город')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер склада')),
                ('operators', models.ManyToManyField(blank=True, related_name='operated_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Операторы')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общее количество')),
                ('available_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доступное количество')),
                ('reserved_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарезервировано')),
                ('min_stock_level', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный запас')),
                ('storage_location', models.CharField(blank=True, help_text='Секция, стеллаж, ячейка', max_length=100, null=True, verbose_name='Место хранения')),
                ('last_restock_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего пополнения')),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.containertype', verbose_name='Тип тары')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='warehouses.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Тара на складе',
                'verbose_name_plural': 'Тара на складах',
                'unique_together': {('warehouse', 'container_type')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('opening_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва')),
                ('pickup_cutoff_time', models.TimeField(help_text='После этого времени заявки на следующий день', verbose_name='Крайний срок приема заявок на забор')),
                ('delivery_cutoff_time', models.TimeField(verbose_name='Крайний срок приема заявок на доставку')),
                ('max_daily_pickups', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум заборов в день')),
                ('max_daily_deliveries', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум доставок в день')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='warehouses.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'График работы по дням',
                'verbose_name_plural': 'Графики работы по дням',
                'unique_together': {('warehouse', 'day_of_week')},
            },
        ),
    ]
