# Generated by Django 5.2.8 on 2026-01-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseschedule',
            name='max_daily_deliveries',
        ),
        migrations.RemoveField(
            model_name='warehouseschedule',
            name='max_daily_pickups',
        ),
    ]
