# Generated by Django 5.2.8 on 2026-01-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_remove_warehouseschedule_max_daily_deliveries_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseschedule',
            options={'ordering': ['warehouse', 'day_of_week'], 'verbose_name': 'График работы по дням', 'verbose_name_plural': 'Графики работы по дням'},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='work_days',
        ),
    ]
