# Generated by Django 5.2.8 on 2026-01-18 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_alter_warehouseschedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='is_24h',
        ),
        migrations.AddField(
            model_name='warehouseschedule',
            name='is_24h',
            field=models.BooleanField(default=False, help_text='Если отмечено, склад работает круглосуточно в этот день', verbose_name='Круглосуточно'),
        ),
        migrations.AlterField(
            model_name='warehouseschedule',
            name='closing_time',
            field=models.TimeField(blank=True, default=datetime.time(20, 0), null=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='warehouseschedule',
            name='delivery_cutoff_time',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Крайний срок приема заявок на доставку'),
        ),
        migrations.AlterField(
            model_name='warehouseschedule',
            name='opening_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='warehouseschedule',
            name='pickup_cutoff_time',
            field=models.TimeField(default=datetime.time(16, 0), help_text='После этого времени заявки на следующий день', verbose_name='Крайний срок приема заявок на забор'),
        ),
    ]
