# Generated by Django 5.2.8 on 2026-01-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_remove_warehouse_is_24h_warehouseschedule_is_24h_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseschedule',
            name='is_24h',
        ),
    ]
