# Generated by Django 5.2.8 on 2026-01-27 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_remove_warehouseschedule_is_24h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseschedule',
            name='delivery_cutoff_time',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True, verbose_name='Крайний срок приема заявок на доставку'),
        ),
        migrations.AlterField(
            model_name='warehouseschedule',
            name='pickup_cutoff_time',
            field=models.TimeField(blank=True, default=datetime.time(16, 0), help_text='После этого времени заявки на следующий день', null=True, verbose_name='Крайний срок приема заявок на забор'),
        ),
    ]
