# Generated by Django 5.2.8 on 2026-01-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0006_alter_warehouseschedule_delivery_cutoff_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseschedule',
            name='delivery_cutoff_time',
        ),
        migrations.RemoveField(
            model_name='warehouseschedule',
            name='pickup_cutoff_time',
        ),
    ]
