# Generated by Django 5.2.8 on 2026-03-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0007_remove_warehouseschedule_delivery_cutoff_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='visible_to_clients',
            field=models.BooleanField(default=False, help_text='Если отмечено, склад будет виден клиентам при создании заявки', verbose_name='Отображать для клиентов'),
        ),
    ]
